version: '3.8'

services:
  php:
    image: php:8.1-fpm
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - database
    ports:
      - "8000:80"

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: login_page
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
